import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between items-center p-4 bg-gray-800">
          <a href="/" className="font-bold text-white-700">Roku's Home</a>
          <div className="space-x-4">
            <a href="/" className="text-white-800 hover:text-yellow-200">Home</a>
            <a href="/" className="text-white-800 hover:text-yellow-200">About</a>
            <a href="/" className="text-white-800 hover:text-yellow-200">Blog</a>
            <a href="/" className="text-white-800 hover:text-yellow-200">Contact me</a>
          </div>
        </nav>

        <main>{children}</main>

        <footer className="text-center text-sm text-gray-500 p-4">
          © 2025 RokuSennyou. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
